#!/bin/bash
exe=${1:-../findent}
$exe -v
rm -f *.try.f
for i in *.f ; do
   echo -n "$i: "
   case "$i" in
      *fixed*) 
	 format="-ffixed-form -ffixed-line-length-none -fd-lines-as-comments"
	 ;;
      *) 
	 format="-ffree-form -ffree-line-length-none" 
	 ;;
   esac

   gfortran -fcoarray=single -cpp $format $i >/dev/null 2>&1
   if [ $? -ne 0 ] ; then
      echo -n " original program does not compile "
   fi

   parms=`head -n1 < $i | tr '!' ' '|tr '\r' ' '`
   $exe $parms < $i > $i.try.f 2>/dev/null
   if [ -f $i.try.f.ref ]; then
      case "$exe" in
	 *.exe)
	    case $i in
	       *dos*)
		  :
		  ;;
	       *)
		  dos2unix -q $i.try.f
		  ;;
	    esac
      esac
      cmp -s $i.try.f $i.try.f.ref >/dev/null 2>&1
      if [ "$?" -eq 0 ]; then
         echo -n "OK"
      else
         echo -n "WRONG"
      fi
      echo
   else
      echo "cannot compare, try running"
      echo "  makereference"
   fi
   case "$i" in
      *free*) 
	 format="-ffree-form -ffree-line-length-none" 
	 ;;
      *) 
	 format="-ffixed-form -ffixed-line-length-none -fd-lines-as-comments"
	 ;;
   esac
   gfortran -fcoarray=single -cpp $format $i.try.f >/dev/null 2>&1
   if [ $? -ne 0 ] ; then
      echo "        converted program does not compile "
   fi
done
