#!/bin/sh
# $Id: makezip 172 2016-12-13 11:20:14Z willem_vermin $
dir=`pwd`
./bootstrap                                                       || exit 1
./configure --with-windows --prefix=$PWD                          || exit 1 
make clean                                                        || exit 1
rm -rf bin
make install-strip                                                || exit 1
version=`./getversion`                                            || exit 1
echo "version = $version"
cd ..                                                             || exit 1
mkdir -p versions                                                 || exit 1
cp findent/README.windows versions/README.txt                     || exit 1
cp findent/bin/findent.exe versions                               || exit 1
cp findent/scripts/wfindent.bat versions                          || exit 1
cp findent/COPYING versions/COPYING.txt
cd versions                                                       || exit 1
unix2dos README.txt COPYING.txt                                   || exit 1
rm -f "findent-$version.zip"
zip   "findent-$version.zip" findent.exe README.txt \
                             COPYING.txt wfindent.bat             || exit 1
rm -f findent.exe README.txt wfindent.bat COPYING.txt
cd "$dir"                                                         || exit 1
make maintainer-clean                                             || exit 1
echo "$0 done"
