#!/bin/bash
# This script assumes that root has created a pbuilder environment
# for sid (and for wheezy and i386-wheezy).
# The configfiles are resp. ~/root/pbuilderrc.sid , 
#  ~/root/pbuilderrc.wheezy and ~/root/pbuilderrc.i386-wheezy.
# This script does not run update.
#
# debian distributions are created in ../debian/
#
curdir=$PWD
version=`./getversion`
echo "version = $version"
tar=$curdir/../versions/findent-$version.tar.gz
dir=findent-$version
if [ x$1 = xall ] ; then
   dists="sid wheezy i386-wheezy"
else
   dists=sid
fi
./maketar  || exit 1
for dist in $dists; do
   debdir=$curdir/../debian/findent-$version-deb.$dist
   rm -rf $debdir
   mkdir -p $debdir || exit 1
   cd $debdir || exit 1
   cp $tar . || exit 1
   tar xf $tar || exit 1
   cp $tar findent_$version.orig.tar.gz || exit 1
   cd $dir || exit 1
   echo building for $dist ...
   pdebuild  --debbuildopts "-us -uc"  -- --configfile ~root/pbuilderrc.$dist \
      --hookdir ~/pbuilderhooks || exit 1
   sudo pbuilder --build --configfile /root/pbuilderrc.sid --buildresult $debdir $debdir/*dsc
   sudo chown -h $USER.$USER $debdir/*
done
echo $0 done
