#!/bin/bash
# $Id: maketar 145 2016-11-13 16:16:33Z willem_vermin $
curdir=`pwd`                                       || exit 1
./bootstrap                                        || exit 1
./configure                                        || exit 1
make maintainer-clean                              || exit 1
rm -rf bin share
./bootstrap                                        || exit 1
export CXX='g++ -m32 -static'                      || exit 1
./configure --prefix=$PWD                          || exit 1
make clean                                         || exit 1
make install-strip                                 || exit 1
unset CXX                                          || exit 1
./configure --with-windows --prefix=$PWD           || exit 1
make clean                                         || exit 1
make install-strip                                 || exit 1
version=`./getversion`                             || exit 1
echo "version = $version"
make distclean                                     || exit 1
cd ..                                              || exit 1
mkdir -p versions                                  || exit 1
cp $curdir/README.1st versions/README              || exit 1
cd versions                                        || exit 1
unix2dos README                                    || exit 1
rm -rf "findent-$version"
cp -r $curdir "findent-$version"                   || exit 1
tar zcf "findent-$version.tgz" "findent-$version"  || exit 1
rm -rf "findent-$version"
echo "$0 done"
