#!/bin/bash
curdir=$PWD
version=$(./getversion)             || exit 1
package=findent
dir=$package
debiandir=${package}-${version}-debian
mkdir -p ../debian
cd ../debian                        || exit 1
rm -rf $debiandir
mkdir -p $debiandir                 || exit 1
cd $debiandir                       || exit 1

mkdir -p $dir                       || exit 1
cd $dir                             || exit 1
cp -r $curdir/* .                   || exit 1

sed -i "1s/(.*)/($version)/" debian/changelog || exit 1

./bootstrap                         || exit 1
./configure                         || exit 1
make maintainer-clean               || exit 1
./bootstrap                         || exit 1

debuild -i -us -uc --lintian-opts --profile debian || exit 1
cd ..                               || exit 1
rm -rf $dir
echo "$0 done"
