#!/bin/bash
# parameter all: produce debs for i386-wheezy, amd64=wheezy, amd64-sid
curdir=$PWD
version=`./getversion`
echo "version = $version"
tar=$PWD/../versions/findent-$version.tar.gz
dir=findent-$version
dsc=findent_$version-1.dsc
debdir=$PWD/../debian/findent-$version-deb
./maketar
if [ -e debian/changelog ] ; then
   sed -i "1s/(.*)/($version-1)/" debian/changelog   || exit 1
fi
rm -rf $debdir
mkdir -p $debdir || exit
cd $debdir || exit
cp $tar . || exit
tar xf $tar || exit
cd $dir || exit
cp -r $curdir/debian . || exit
dh_make --yes --s -f $tar
debuild -us -uc --lintian-opts --profile debian || exit
# dpkg-buildpackage -us -uc
if test "x$1" != xall ; then 
   cd ..
   rm -r $dir || exit 1
   exit 0
fi
cd ..
pwd
#for dist in sid ; do
for dist in i386-wheezy amd64-wheezy amd64-sid ; do
   echo building for $dist ...
   sudo bash `which pbuilder` --build --configfile ~root/pbuilderrc.$dist $dsc || exit 1
   debsign /var/cache/pbuilder/result-$dist/findent_$version-1_*.changes || exit 1
done
rm -r $dir || exit 1
echo '***********************************************************'
echo '** i386-wheezy in /var/cache/pbuilder/result-i386-wheezy **'
echo '** wheezy in /var/cache/pbuilder/result-amd64-wheezy     **'
echo '** sid in /var/cache/pbuilder/result-amd64-sid           **'
echo '***********************************************************'
echo $0 done
